site: jekyll-theme-archive
url: shekelash.github.io #你的博客网址，必填
title: jekyll-theme-archive #你的博客标题，必填
description: #博客介绍，留空则自动引用项目页的介绍
author: #别填
  name: ShekelAsh #用户名，建议填
  email: 1111@1111.com
  url: site-url
permalink: pretty

baseurl: "" #用于非根目录博客，例"/ABC"

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

google_analytics:
  tracking_id: UA-133439443-2
